import { createOrder, listBranchReplenishmentOrders, listOrders, listWarehouseOrders } from "@/server/orders/repository";
import { articleIds, body, notes, orderStatus } from "@/server/orders/request";
import { getAuthorizedContext, getAuthorizedScope } from "@/server/auth/scope";
import { ForbiddenError } from "@/server/auth/errors";
import { canAccessBranch, canConfirmReplenishment } from "@/server/auth/policies";
import { parseOptionalCalendarDate, parseOptionalPositiveInteger, parsePagination, parseSearch } from "@/server/validation/request";
import { apiResponse } from "../dashboard/_shared";

export const runtime = "nodejs";
export async function GET(request: Request) { const params = new URL(request.url).searchParams; return apiResponse(async () => { const context = await getAuthorizedContext(); const pagination = parsePagination(params); const status = params.get("status") ? orderStatus(params.get("status")) : undefined; if (params.get("warehouse") === "1") { if (!canAccessBranch(context, 1)) throw new ForbiddenError(); return { ...await listWarehouseOrders({ status, originBranchId: parseOptionalPositiveInteger(params.get("origin_branch_id"), "origin_branch_id"), planningDate: parseOptionalCalendarDate(params.get("planning_date"), "planning_date"), search: parseSearch(params.get("search")), readyToDispatch: params.get("ready") === "1", limit: pagination.limit, offset: pagination.offset }), page: pagination.page, limit: pagination.limit }; } if (params.get("pv") === "1") { const branch = parseOptionalPositiveInteger(params.get("origin_branch_id"), "origin_branch_id") ?? context.memberships.find((m) => m.role === "PV_OPERATOR")?.branchId; if (!branch || !canConfirmReplenishment(context, branch)) throw new ForbiddenError(); return { ...await listBranchReplenishmentOrders(branch, { status, planningDate: parseOptionalCalendarDate(params.get("planning_date"), "planning_date"), activeOnly: params.get("active") === "1", limit: pagination.limit, offset: pagination.offset }), page: pagination.page, limit: pagination.limit }; } const { scope } = await getAuthorizedScope(params); return { ...await listOrders(scope, { status, search: parseSearch(params.get("search")), from: parseOptionalCalendarDate(params.get("from"), "from"), to: parseOptionalCalendarDate(params.get("to"), "to"), limit: pagination.limit, offset: pagination.offset }), page: pagination.page, limit: pagination.limit }; }); }
export async function POST(request: Request) { const params = new URL(request.url).searchParams; return apiResponse(async () => { const context = await getAuthorizedContext(); const branch = context.memberships.find((m) => m.role === "PV_OPERATOR")?.branchId; if (!branch || !canConfirmReplenishment(context, branch)) throw new ForbiddenError(); const { scope } = await getAuthorizedScope(params); const input = await body(request); return { id: await createOrder(scope, articleIds(input.article_ids), notes(input.notes), String(context.userId)) }; }); }
