import { removeItem, updateItemQuantity, updateOperationalQuantity } from "@/server/orders/repository";
import { body, id, operationalQuantity, quantity } from "@/server/orders/request";
import { getAuthorizedContext, getAuthorizedScope } from "@/server/auth/scope";
import { getAuthorizedOrder, toPolicyOrder } from "@/server/auth/orders";
import { canModifyOrder, canPrepareOrder } from "@/server/auth/policies";
import { ForbiddenError } from "@/server/auth/errors";
import { apiResponse } from "../../../../dashboard/_shared";
export const runtime = "nodejs";
export async function PATCH(request: Request, context: { params: Promise<{ id: string; itemId: string }> }) { const params = new URL(request.url).searchParams; return apiResponse(async () => { const route = await context.params; const auth = await getAuthorizedContext(); const scope = (await getAuthorizedScope(params)).scope; const orderId = id(route.id, "id"); const order = await getAuthorizedOrder(auth, scope, orderId); const input = await body(request); const operational = input.approved_quantity !== undefined || input.prepared_quantity !== undefined; if (!(operational ? canPrepareOrder(auth, toPolicyOrder(order)) : canModifyOrder(auth, toPolicyOrder(order)))) throw new ForbiddenError(); const itemId = id(route.itemId, "itemId"); const actorId = String(auth.userId); if (input.approved_quantity !== undefined) await updateOperationalQuantity(scope, orderId, itemId, "approved_quantity", operationalQuantity(input.approved_quantity, "approved_quantity"), actorId); else if (input.prepared_quantity !== undefined) await updateOperationalQuantity(scope, orderId, itemId, "prepared_quantity", operationalQuantity(input.prepared_quantity, "prepared_quantity"), actorId); else await updateItemQuantity(scope, orderId, itemId, quantity(input.requested_quantity), actorId); return { ok: true }; }); }
export async function DELETE(request: Request, context: { params: Promise<{ id: string; itemId: string }> }) { const params = new URL(request.url).searchParams; return apiResponse(async () => { const route = await context.params; const auth = await getAuthorizedContext(); const scope = (await getAuthorizedScope(params)).scope; const orderId = id(route.id, "id"); const order = await getAuthorizedOrder(auth, scope, orderId); if (!canModifyOrder(auth, toPolicyOrder(order))) throw new ForbiddenError(); await removeItem(scope, orderId, id(route.itemId, "itemId"), String(auth.userId)); return { ok: true }; }); }
